os:
  - linux

# This makes us use Ubuntu 14 instead of 12
dist: trusty

language: c
script:
  - sudo apt-get update
  - sudo apt-get install libgtk-3-dev -y || sudo apt-cache search libgtk3
  - make -f GNUmakefile
  - make -f GNUmakefile examples
  - make -f GNUmakefile test 

# TODO osx
# need to figure out how to force language: objective-c and turn off the apt-get rules
