
# This makes us use Ubuntu 14 instead of 12
dist: trusty

language: cpp
script:
  - sudo apt-get update
  - sudo apt-get install libgtk-3-dev -y || sudo apt-cache search libgtk3
  - make -f GNUmakefile
  - make -f GNUmakefile example EXAMPLE=histogram

# Only working things are added here... Some interesting commands would be:
#  - make -f GNUmakefile examples
#  - make -f GNUmakefile test
#
# But they both won't work
