os:
  - linux
  - osx

# This makes us use Ubuntu 14 instead of 12
dist: trusty

language: c
script:
  - test Z$TRAVIS_OS_NAME = Zlinux && sudo apt-get update
  - test Z$TRAVIS_OS_NAME = Zlinux && { sudo apt-get install libgtk-3-dev -y || sudo apt-cache search libgtk3; }
  - make -f GNUmakefile
  - make -f GNUmakefile examples
  - make -f GNUmakefile test 
