language: c

include: &toolchain_linux_amd64
  os: linux
  dist: trusty
  addons:
    apt:
      packages:
        - libgtk-3-dev

include: &toolchain_linux_386
  os: linux
  dist: trusty
  addons:
    apt:
      packages:
        - gcc-multilib
        - g++-multilib
        - libgtk-3-dev:i386
        # the rest fixes broken dependencies of libgtk:i386
        - libgirepository-1.0-1:i386
        - libglib2.0-dev:i386
        - gir1.2-glib-2.0:i386
        - gir1.2-atk-1.0:i386
        - libatk1.0-dev:i386
        - libfreetype6-dev:i386
        - libfontconfig1-dev:i386
        - libcairo2-dev:i386
        - libgdk-pixbuf2.0-dev:i386
        - libpango1.0-dev:i386
        - libxft-dev:i386
        - libpng12-dev:i386

include: &toolchain_osx_amd64
  os: osx
  osx_image: xcode8

# Travis CI build matrix.
# Each entry below will trigger an extra, parallel build on Travis.
matrix:
  include:
    - env: linking=shared platform=amd64
      <<: *toolchain_linux_amd64
    - env: linking=static platform=amd64
      <<: *toolchain_linux_amd64
    - env: linking=shared platform=386
      <<: *toolchain_linux_386
    - env: linking=static platform=386
      <<: *toolchain_linux_386
    - env: linking=shared platform=amd64
      <<: *toolchain_osx_amd64
    - env: linking=static platform=amd64
      <<: *toolchain_osx_amd64

install:
  - if [[ "${platform}" == "386" ]]; then
      export CFLAGS=-m32;
      export CXXFLAGS=-m32;
      export PKG_CONFIG_PATH=/usr/lib/i386-linux-gnu/pkgconfig;
    fi
  - if [[ "${linking}" == "static" ]]; then
      export CMAKE_FLAGS=-DBUILD_SHARED_LIBS=OFF;
    fi

script:
  - cmake --version
  - mkdir build
  - pushd build && cmake ${CMAKE_FLAGS} .. && make tester examples && popd

after_success:
  - ls -lR build/out
  - file build/out/test
